### ISSUE TITLE
" undefined method `date_add_sql_append'" when in multithreaded mode

### ISSUE THREAD

**Issue by HoneyryderChuck** [janko/sequel-activerecord_connection#13]
I've been [revamping the `rodauth-oauth`  test suite in order to exercise the test suite under different ruby/rails combos](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/merge_requests/48). Before that, all tests ran in multiple threads (the minitest parallel mode), except for tests using sqlite memory store. However, since enabling the tests for rails mode, I started seeing the error message mentioned in the title in the test suite.

Here's an [example of a CI run with the issue](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/jobs/843900113). Feel free to inspect the whole pipeline.

This error seems to happen often (specially in older ruby/rails combos). I've disabled multi-threading in order to move ahead.

The error has to do with the `:date_arithmetic` sequel plugin, which is loaded in the rodauth context. I'm guessing this issue never surfaced because the test suite isn't run concurrently?

**Comment by janko** [comment]
I don't know what is causing these issues in multithreaded tests, but I don't think this is an issue with sequel-activerecord_connection.

Did you try loading the extension upfront, right after creating the Sequel database object?

**Comment by HoneyryderChuck** [comment]
I've narrowed it down to a potential issue in this gem, because I don't have any issue when running tests with plain rodauth and sequel, and this is a sequel dataset-specific issue, so no rails.

I've noticed that I'm not using the latest version (0.4.2 instead of 1.1.0), but [inspecting rubygems I don't find the more recent](https://rubygems.org/search?utf8=%E2%9C%93&query=rodauth-rails). Have they been published to rubygems already?

**Comment by janko** [comment]
0.4.2 is the latest rodauth-rails version, 1.1.0 is the latest sequel-activerecord_connection version.

What could also be problematic is that you're changing the `Rodauth::Rails.app` global, which might not be thread-safe.

If you want to pinpoint whether the issue is in rodauth-rails or here, I suggest modifying you Roda & Sequel tests to source the Sequel connection from Active Record, and see if the tests pass.

**Comment by HoneyryderChuck** [comment]
> 0.4.2 is the latest rodauth-rails version, 1.1.0 is the latest...

Yes, I think I was  already in "sleep mode" when I wrote that, sorry about the confusion.

> What could also be problematic is that you're changing the Rodauth::Rails.app global, which might not be thread-safe.

Indeed, that might explain the issues I had with runnning it with sqlite. And come to think of it, that means I can't test concurrently with rails **at all**, as rails applications are singletons, and either I treat it as an immutable application and enable multithread mode, or I don't. Changing the rodauth app in the setup process does mean that I can't have ice things :( 

Nevertheless, I've seen disabled multithreading in the rails suites, and I still [keep seeing the issue, albeit more sporadically](What could also be problematic is that you're changing the Rodauth::Rails.app global, which might not be thread-safe.).

> I suggest modifying your Roda & Sequel tests to source the Sequel connection from Active Record, and see if the tests pass.

I didn't understand the suggestion. The test already exercise the sequel db instance with the `sequel-activerecord_connection` plugin, so I'd say they're already doing that (?).

I guess I'll have to get a deeper look into this, as it's not really trivial to pinpoint: the `:date_arithmetic` is added as part of the rodauth `post_configure` hook, so I'm out of ideas. I'll see what I can come up with.

**Comment by janko** [comment]
> The test already exercise the sequel db instance with the sequel-activerecord_connection plugin, so I'd say they're already doing that (?).

In [`test/support/roda_integration.rb`](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/master/test/support/roda_integration.rb), I just see the Sequel connection be created directly, without any Active Record or `activerecord_connection` extension being used. If you try using `activerecord_connection` extension there, that will prove whether the problem is in this gem or elsewhere.

> I guess I'll have to get a deeper look into this, as it's not really trivial to pinpoint: the :date_arithmetic is added as part of the rodauth post_configure hook, so I'm out of ideas.

I would try loading the `date_arithmetic` extension right after creating the Sequel database object. You could even put a `Sequel.synchronize` block around connecting and adding the extension, to ensure no other thread can retrieve that `Sequel::Database` object before the `date_arithmetic` extension was applied.

**Comment by HoneyryderChuck** [comment]
> In test/support/roda_integration.rb, I just see the Sequel connection being created directly, 

Thats the connection I use for the off-the-rails tests (when `rails_integration` is loaded, Rails takes over its own connection, loads `rodauth-rails`,  which [loads its own sequel db instance connection to the AR connection](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/master/test/rails_app/config/initializers/sequel.rb#L26), and is picked up to [be used to run the migration (again)](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/master/test/support/rails_integration.rb#L15) and [used in the remaining db operations](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/master/test/support/rails_integration.rb#L65). All this to say, when rails is picked up, the  initial DB var you mention isn't used for anything else.

Right now the rails setup is a bit convoluted, so apologies if it looks confusing. I'm still in the process of fixing this state of affairs.

> I would try loading the date_arithmetic extension right after creating the Sequel database object. 

As per my explanation above, I'm not connecting myself (the `RAILSDB` is instantiated in the rails initializer). The `:date_arithmetic` plugin will be applied [when this block gets instantiated](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/blob/master/test/support/rails_integration.rb#L40), as part of the rodauth feature `post_configure` hook. I'm not sure, given this scenario, whether loading the plugin in the rails initializer is the best way to prevent this, and I'd also rather not recommend users doing it.

I'll see about reducing that `DB` var noise from the rails tests path, and see whether that improves things.

**Comment by HoneyryderChuck** [comment]
Just to let you know: I've since [found a way to disable running the migration with that DB instance in Rails mode](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/merge_requests/50), and [the extended test suite ran flawlessly](https://gitlab.com/honeyryderchuck/rodauth-oauth/-/pipelines/215363693).

I'm not sure yet how those two sequel db instances were interfering with each other. I've check both `rodauth-rails` and `sequel-activerecord_connection` looking for references to any `DB` var, found nothing. My only guess is that, somehow, the rails initialization process ran before I set the rails roda application in `rails_integration`, and rodauth init ran with `Sequel::DATABASES.first` instead of with `RAILSDB`. It's a big, but it might have to do with the generator tests and whether they load the rails application to run those tests before any other oauth test runs. Big guess.

I'll close this, as this is not a `rodauth-rails` anymore. I'm sad overall that I can't run these tests in multithreaded mode though, but I guess there's no way to go around it (the rails singleton application limitations strike again).

Thx fo the support @janko
