### ISSUE TITLE
When an AR query causes a Sequel transaction to abort, connexion becomes unusable

### ISSUE THREAD

**Issue by renchap** [janko/sequel-activerecord_connection#15]
Failing test in `postgres_test.rb` to reproduce the issue:

```ruby
  it "handles transaction abortions from Active Record queries inside transaction" do
    activerecord_model = Class.new(ActiveRecord::Base)
    activerecord_model.table_name = :records

    @db.transaction do |conn|
      activerecord_model.create(col: "foo", time: Time.new(2021, 1, 10))
      record = activerecord_model.connection.exec_query("SELECT * FROM records").first

      begin
        activerecord_model.create(id: record["id"], col: "foo", time: Time.new(2021, 1, 10))
      rescue ActiveRecord::RecordNotUnique
        # Do nothing
      end

      record = activerecord_model.connection.exec_query("SELECT * FROM records").first

      assert_equal "foo",                 record["col"]
      assert_equal Time.new(2021, 1, 10), record["time"]
    end
  end
```

The second `create` will fail because this `id` already exists.
`ActiveRecord::RecordNotUnique` is properly thrown, but if we continue to run queries in this connection they fail with
```
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

I hit this issue when using some AR `create` calls in a Rodauth `change_login` block (wrapped in a Sequel transaction) where the record I want to insert might exists. I am not sure what the proper fix could be here, if there is any :/

**Comment by janko** [comment]
Yes, this is actually how Postgres transactions behave, a failed statement inside a transaction will cause any subsequent statements inside the same transaction to fail. The following script reproduces this with pure Active Record:

```rb
require "active_record"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "sequel")

ActiveRecord::Schema.define do
  create_table :records, force: true do |t|
  end
end

class Record < ActiveRecord::Base
end

ActiveRecord::Base.transaction do
  record = Record.create!

  begin
    Record.create!(id: record.id)
  rescue ActiveRecord::RecordNotUnique
  end

  Record.all.to_a # => ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
end
```

You can work around this by using savepoints, which is also what [Rodauth uses internally](https://github.com/jeremyevans/rodauth/blob/3b661c19160f826187d7034520eb3171b57f192a/lib/rodauth/features/base.rb#L701-L706) when it wants to handle uniqueness constraint violations.

```rb
  # ...
  begin
    ActiveRecord::Base.transaction(requires_new: true) do # creates a savepoint
      Record.create!(id: record.id)
    end
  rescue ActiveRecord::RecordNotUnique
  end
  # ...
```

**Comment by renchap** [comment]
Thanks a lot, it indeed makes sense and I did not knew about savepoints, I learned something. And it definitely will solve my issues :)
