### ISSUE TITLE
github discussions, initial set up

### ISSUE THREAD

**Issue by benkoshy** [janko/sequel-activerecord_connection#19]
Hi Janko

Would you be opposed to opening up github  discussions for this repo? This would allow people to ask/receive support from the community (as it grows)

Also I don't know where I should put this code (in a rails project) - I can make a PR if required.

```rb
# config/initializers/sequel.rb ## should it go here??
require "sequel"
DB = Sequel.postgres(extensions: :activerecord_connection)
```

(Appreciate the work you've put into this library)

**Comment by janko** [comment]
Hi Ben 👋🏻 That's a good point, I just opened the discussions. I also added a note in the README that the code should go into an initializer, like you correctly assumed 😉
