### ISSUE TITLE
Error when using rodauth-rails with ruby-oci8

### ISSUE THREAD

**Issue by k-graefenhain** [janko/sequel-activerecord_connection#29]
I use rodauth-rails (1.15.0) with sequel-activerecord_connection (1.4.1) and sequel (5.84.0).

When trying to login I get the following error message:
"undefined method `raw_oci_connection' for an instance of OCI8EnhancedAutoRecover"

I tried with ruby-oci8 (2.2.14) and (2.2.13 x64-mingw-ucrt). Any suggestions how I can solve the issue?

**Comment by k-graefenhain** [comment]
Yes, with the actual version from the `sequel-activerecord_connection` master branch it works! Thanks a lot!

**Comment by janko** [comment]
Great, just released version 1.4.2 with the fix.
